server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost/merchant?useSSL=false
    password: merchant
    username: merchant
    driver-class-name: com.mysql.jdbc.Driver

services:
  notificationService:
    baseUri: http://nabhackathon-notifications.cfapps.io
    notifyPath: /notify